title: Curriculum Vitae
author:
  name: Álvaro R. Puente-Uriona
  email: irukoa@live.com
description: "My digital CV"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
